ARG TF_GPU_IMAGE=tensorflow/tensorflow:latest-gpu
FROM ${TF_GPU_IMAGE}

WORKDIR /workspace

COPY requirements /workspace/requirements
RUN python -m pip install --upgrade pip && \
    pip install --no-cache-dir -r /workspace/requirements/base.txt

COPY . /workspace
RUN pip install --no-cache-dir -e .

ENTRYPOINT ["/workspace/docker/entrypoint.sh"]
